### ISSUE TITLE
When erroneous data is pulled, previously useful (even if old) data is erased

### ISSUE THREAD

**Issue by will1982** [dandalpiaz/transit-cu#8]
Reproduce:
Visit a 'stop' page (e.g. https://transitcu.com/stop=ISR_Illinois%20Street%20Residence%20Hall)
Wait for Data error to occur
Page is overwritten with error message, precluding user from accessing any times

Personally, I would simply keep the old data w/ a warning that's it out of date

**Comment by dandalpiaz** [comment]
Thank you for the feedback. I like the idea of keeping the old data around to give at least some point of reference. I think I'll try to include a timestamp closer to the top of the page as well, so users will see how stale the data is if there are errors.

As a side note, it sounds like the API was having some issues yesterday, and is still having some intermittent issues today. Hopefully they can get it resolved soon.

**Comment by will1982** [comment]
Agree! Since the MTD API is rather unstable, I've been taking screenshots of your site and using the computer clock as a reference point 😂

Overall, though, this website is fantastic. I use it every day and the only times it lets me down is when the MTD API is down (which is no fault of yours). I wonder why their API is so unstable.
Cheers!

**Comment by dandalpiaz** [comment]
Glad to hear it!

The old data should now be kept on the screen if there's an error retrieving newer data.
